llm:
  api_base: "https://openrouter.ai/api/v1"
  api_key: "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"
  models:
    - name: "openai/gpt-5.2"
    # - name: "openai/gpt-5.1-codex-max"
    # - name: "deepseek/deepseek-v3.2-speciale"
    # - name: "meta-llama/llama-3.1-405b-instruct:free"
    # - name: "qwen/qwen3-coder:free"
      weight: 1.0

database:
  db_path: "examples/self_convolution_50/openevolve_output/db"
  log_prompts: true
  feature_dimensions:
    - "size"
    - "max_norm"
    - "self_convolution_L1"
    - "self_convolution_L2sq"
    - "self_convolution_Linf"
  population_size: 200
  num_islands: 3

evaluator:
  timeout: 300
  cascade_evaluation: false

prompt:
  template_dir: "examples/self_convolution_50/templates"

diff_based_evolution: false

max_iterations: 100